# Generated by Django 6.1 on 2026-08-22 03:55

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0014_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingArticle',
            fields=[
            ],
            options={
                'verbose_name': 'Bài viết Marketing',
                'verbose_name_plural': 'Bài viết Marketing',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('booking.article',),
        ),
    ]
