from django.db import connection

sql = '''
CREATE TABLE "db_table_clinic" (
    "clinic_id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL,
    "address" text NULL,
    "hotline" varchar(12) NULL,
    "map_url" varchar(500) NULL,
    "total_chairs" integer NOT NULL,
    "created_on" timestamp with time zone NOT NULL
);
'''

with connection.cursor() as cursor:
    cursor.execute(sql)

print("Clinic table created successfully.")