# Generated by Django 6.1 on 2026-08-22 03:26

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0013_alter_bookingstatus_status_alter_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageBooking',
            fields=[
            ],
            options={
                'verbose_name': 'Chi tiết Bookings',
                'verbose_name_plural': 'Chi tiết Bookings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('booking.booking',),
        ),
    ]
