# Generated by Django 6.1 on 2026-08-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_alter_article_content'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
            ],
            options={
                'verbose_name': 'Lịch Ngày',
                'verbose_name_plural': 'Lịch Ngày',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('booking.booking',),
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
            ],
            options={
                'verbose_name': 'Lịch Tuần',
                'verbose_name_plural': 'Lịch Tuần',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('booking.booking',),
        ),
    ]
