# Generated by Django 6.1 on 2026-08-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0023_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategoryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Danh mục dịch vụ',
                'verbose_name_plural': 'Danh mục dịch vụ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('booking.servicecategory',),
        ),
        migrations.CreateModel(
            name='ServiceDetailProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Chi tiết dịch vụ',
                'verbose_name_plural': 'Chi tiết dịch vụ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('booking.servicedetail',),
        ),
    ]
