# Generated by Django 6.1 on 2026-08-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
        migrations.AlterModelTable(
            name='booking',
            table='bookings',
        ),
        migrations.AlterModelTable(
            name='bookingbill',
            table='booking_bill',
        ),
        migrations.AlterModelTable(
            name='bookingstatus',
            table='booking_status',
        ),
        migrations.AlterModelTable(
            name='clinic',
            table='clinic',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
        migrations.AlterModelTable(
            name='inventorydetail',
            table='inventory_details',
        ),
        migrations.AlterModelTable(
            name='inventoryusage',
            table='inventory_usage',
        ),
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
        migrations.AlterModelTable(
            name='timeslot',
            table='time_slots',
        ),
    ]
