# Generated by Django 6.1 on 2026-08-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_article_table_alter_booking_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='db_table_articles',
        ),
        migrations.AlterModelTable(
            name='booking',
            table='db_table_bookings',
        ),
        migrations.AlterModelTable(
            name='bookingbill',
            table='db_table_booking_bill',
        ),
        migrations.AlterModelTable(
            name='bookingstatus',
            table='db_table_booking_status',
        ),
        migrations.AlterModelTable(
            name='clinic',
            table='db_table_clinic',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='db_table_customers',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='db_table_employees',
        ),
        migrations.AlterModelTable(
            name='inventorydetail',
            table='db_table_inventory_details',
        ),
        migrations.AlterModelTable(
            name='inventoryusage',
            table='db_table_inventory_usage',
        ),
        migrations.AlterModelTable(
            name='service',
            table='db_table_services',
        ),
        migrations.AlterModelTable(
            name='timeslot',
            table='db_table_time_slots',
        ),
    ]
