# Generated by Django 6.1 on 2026-08-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_article_table_alter_booking_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='chair_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số ghế'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='total_chairs',
            field=models.IntegerField(default=5, verbose_name='Tổng số ghế'),
        ),
    ]
