# Generated by Django 6.1 on 2026-08-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_chair_number_clinic_total_chairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='map_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Google Map'),
        ),
    ]
