# Generated by Django 6.1 on 2026-08-22 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_clinic_map_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100, null=True, verbose_name='Khách hàng')),
                ('service_name', models.CharField(max_length=100, null=True, verbose_name='Dịch vụ')),
                ('booking_date', models.DateField(verbose_name='Ngày khám')),
                ('start_time', models.TimeField(verbose_name='Bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Kết thúc')),
                ('latest_status', models.CharField(max_length=20, null=True, verbose_name='Trạng thái hiện tại')),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Đã thu')),
            ],
            options={
                'verbose_name': 'Chi tiết Booking',
                'verbose_name_plural': 'Chi tiết Bookings',
                'db_table': 'db_table_booking_details_view',
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='bookingstatus',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bookingstatus',
            name='changed_by',
        ),
        migrations.AddField(
            model_name='bookingstatus',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chA'),
        ),
        migrations.AlterField(
            model_name='bookingstatus',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('CheckIn', 'CheckIn'), ('Success', 'Success'), ('Cancelled', 'Cancelled')], default='Booked', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='S` ti?n')),
                ('payment_method', models.CharField(choices=[('QR Code', 'QR Code'), ('Cash', 'Cash'), ('Card', 'Card')], default='QR Code', max_length=50, verbose_name='Phng thc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.booking')),
            ],
            options={
                'db_table': 'db_table_payments',
            },
        ),
        migrations.DeleteModel(
            name='BookingBill',
        ),
    ]
