# Generated by Django 6.1 on 2026-08-22 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_bookingdetails_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE VIEW db_table_booking_details_view AS
            SELECT 
                b.id as booking_id,
                c.full_name as customer_name,
                s.name as service_name,
                b.booking_date,
                b.start_time,
                b.end_time,
                (
                    SELECT status FROM db_table_booking_status bs 
                    WHERE bs.booking_id = b.id 
                    ORDER BY bs.created_at DESC LIMIT 1
                ) as latest_status,
                COALESCE((
                    SELECT SUM(amount) FROM db_table_payments p 
                    WHERE p.booking_id = b.id
                ), 0) as total_paid
            FROM db_table_bookings b
            LEFT JOIN db_table_customers c ON b.customer_id = c.id
            LEFT JOIN db_table_services s ON b.service_id = s.id;
            """,
            reverse_sql="DROP VIEW IF EXISTS db_table_booking_details_view;"
        )
    ]
