# Generated by Django 6.1 on 2026-08-22 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_create_booking_details_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50, verbose_name='Tên ngân hàng (Mã)')),
                ('account_number', models.CharField(max_length=50, verbose_name='Số tài khoản')),
                ('account_name', models.CharField(max_length=100, verbose_name='Tên tài khoản')),
                ('is_default', models.BooleanField(default=False, verbose_name='Mặc định')),
            ],
            options={
                'verbose_name': 'Cấu hình Thanh toán',
                'verbose_name_plural': 'Cấu hình Thanh toán',
                'db_table': 'db_table_payment_config',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_bookings', to='booking.employee', verbose_name='Bác sĩ khám'),
        ),
        migrations.AlterField(
            model_name='bookingstatus',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('QR Code', 'QR Code'), ('Cash', 'Cash'), ('Card', 'Card')], default='QR Code', max_length=50, verbose_name='Phương thức'),
        ),
    ]
