# Generated by Django 6.1 on 2026-08-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_update_booking_details_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Giá dịch vụ'),
        ),
    ]
