# Generated by Django 6.1 on 2026-08-22 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_service_price'),
    ]

    operations = [
        migrations.RunSQL("DROP VIEW IF EXISTS db_table_booking_details_view;"),
        migrations.DeleteModel(
            name='BookingDetails',
        ),
    ]
