# Generated by Django 6.1 on 2026-08-22 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_delete_bookingdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentConfig',
            new_name='TopupInfo',
        ),
        migrations.AlterModelTable(
            name='topupinfo',
            table='db_table_topup_info',
        ),
    ]
