# Generated by Django 6.1 on 2026-08-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_rename_paymentconfig_topupinfo_alter_topupinfo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstatus',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('paid', 'paid'), ('cancelled', 'cancelled')], default='booked', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền'),
        ),
    ]
