# Generated by Django 6.1 on 2026-08-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_bookingstatus_status_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Reception', 'Reception'), ('Marketing', 'Marketing')], default='Doctor', max_length=20, verbose_name='Vai trò'),
        ),
    ]
