# Generated by Django 6.1 on 2026-08-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(db_index=True, verbose_name='Ngày khám'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(db_index=True, verbose_name='Bắt đầu'),
        ),
    ]
