# Generated by Django 6.1 on 2026-08-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_booking_booking_date_alter_booking_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Focus Keyword'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title'),
        ),
    ]
