# Generated by Django 6.1 on 2026-08-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_article_focus_keyword_article_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', 'Bản nháp'), ('Published', 'Xuất bản')], default='Draft', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='article',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='temp/', verbose_name='Tải lên File Word (.docx)'),
        ),
    ]
