# Generated by Django 6.1 on 2026-08-23 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_alter_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên dịch vụ')),
                ('estimate_time', models.IntegerField(default=30, verbose_name='Thời gian (phút)')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Danh mục Dịch vụ',
                'verbose_name_plural': 'Danh mục Dịch vụ',
                'db_table': 'db_table_service_categories',
            },
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã dịch vụ')),
                ('name', models.CharField(max_length=150, verbose_name='Tên dịch vụ chi tiết')),
                ('difficulty', models.CharField(choices=[('Cơ bản', 'Cơ bản'), ('Dễ', 'Dễ'), ('Trung bình', 'Trung bình'), ('Khó', 'Khó'), ('Phức tạp', 'Phức tạp')], default='Cơ bản', max_length=20, verbose_name='Độ khó')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá dịch vụ')),
                ('warranty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bảo hành')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='booking.servicecategory', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Chi tiết Dịch vụ',
                'verbose_name_plural': 'Chi tiết Dịch vụ',
                'db_table': 'db_table_service_details',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.servicedetail'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
