# Generated by Django 6.1 on 2026-08-23 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_servicecategory_servicedetail_alter_booking_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.servicecategory', verbose_name='Nhóm dịch vụ (Khách chọn)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.servicedetail', verbose_name='Dịch vụ chi tiết'),
        ),
    ]
