# Generated by Django 6.1 on 2026-08-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_remove_booking_service_booking_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số tiền thực tế'),
        ),
    ]
