# Generated by Django 6.1 on 2026-08-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_booking_actual_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bookingstatus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bookingstatus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inventorydetail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inventoryusage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='id',
        ),
        migrations.RemoveField(
            model_name='topupinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='article',
            name='article_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='bookingstatus',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingstatus',
            name='status_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='clinic',
            name='clinic_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Giới tính'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='inventory_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='inventoryusage',
            name='usage_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='service_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='slot_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='topupinfo',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='topupinfo',
            name='topup_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='hotline',
            field=models.CharField(max_length=20, verbose_name='Hotline'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='map_url',
            field=models.TextField(blank=True, null=True, verbose_name='Google Map URL'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên phòng khám'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='total_chairs',
            field=models.IntegerField(default=1, verbose_name='Số ghế nha khoa'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryusage',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='estimate_time',
            field=models.IntegerField(default=30, verbose_name='Thời gian dự kiến (phút)'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên danh mục'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã dịch vụ'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='difficulty',
            field=models.CharField(choices=[('Cơ bản', 'Cơ bản'), ('Dễ', 'Dễ'), ('Trung bình', 'Trung bình'), ('Khó', 'Khó'), ('Phức tạp', 'Phức tạp')], default='Cơ bản', max_length=50, verbose_name='Độ khó'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên dịch vụ'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá tiền'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='warranty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bảo hành'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterModelTable(
            name='clinic',
            table='db_table_clinics',
        ),
    ]
