# Generated by Django 6.1 on 2026-08-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_remove_article_id_remove_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Reception', 'Reception'), ('Marketing', 'Marketing'), ('Accountant', 'Kế toán')], default='Doctor', max_length=20, verbose_name='Vai trò'),
        ),
    ]
