# Generated by Django 6.1 on 2026-08-24 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_alter_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='inventorydetail',
            name='inventory_id',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='slot_id',
        ),
        migrations.RemoveField(
            model_name='topupinfo',
            name='created_on',
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='timeslot_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.servicecategory'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.servicedetail'),
        ),
        migrations.AlterField(
            model_name='bookingstatus',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='hotline',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Hotline'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='map_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Google Map'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên chi nhánh'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='total_chairs',
            field=models.IntegerField(default=5, verbose_name='Tổng số ghế'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Reception', 'Reception'), ('Marketing', 'Marketing')], default='Doctor', max_length=20, verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventoryusage',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='estimate_time',
            field=models.IntegerField(default=30, verbose_name='Thời gian ước tính (phút)'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên danh mục'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='booking.servicecategory', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã dịch vụ'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên dịch vụ chi tiết'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bảo hành'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='servicedetail',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_service_detail'),
        ),
        migrations.AlterModelTable(
            name='clinic',
            table='db_table_clinic',
        ),
    ]
