# Generated by Django 6.1 on 2026-08-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_remove_customer_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mã dịch vụ'),
        ),
    ]
