# Generated by Django 6.1 on 2026-08-24 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_alter_servicedetail_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('discount_type', models.CharField(choices=[('Percent', 'Phần trăm'), ('Fixed', 'Số tiền')], default='Percent', max_length=20, verbose_name='Loại giảm giá')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá trị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Khuyến mãi',
                'verbose_name_plural': 'Khuyến mãi',
                'db_table': 'db_table_discounts',
            },
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Đơn giá')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='booking.booking')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.servicedetail')),
            ],
            options={
                'verbose_name': 'Dịch vụ trong Lịch',
                'verbose_name_plural': 'Các dịch vụ',
                'db_table': 'db_table_booking_details',
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billing_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng tiền gốc (Hệ thống tính)')),
                ('manual_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tổng tiền thu thực tế (Nhập tay)')),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Số tiền điều chỉnh')),
                ('final_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Số tiền cuối cùng')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='booking.booking', verbose_name='Lịch khám')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.discount', verbose_name='Khuyến mãi')),
            ],
            options={
                'verbose_name': 'Hóa đơn Kế toán',
                'verbose_name_plural': 'Hóa đơn Kế toán',
                'db_table': 'db_table_billing',
            },
        ),
    ]
