# Generated by Django 6.1 on 2026-08-24 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_discount_bookingdetail_billing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdetail',
            old_name='price',
            new_name='actual_price',
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='service',
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='service_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.servicedetail', verbose_name='Dịch vụ'),
        ),
    ]
