# Generated by Django 6.1 on 2026-08-24 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_rename_price_bookingdetail_actual_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='doctor',
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'Doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.employee', verbose_name='Bác sĩ khám'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='actual_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Đơn giá'),
        ),
    ]
