# Generated by Django 6.1 on 2026-08-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_remove_booking_actual_price_remove_booking_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Mã giảm giá'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã dịch vụ'),
        ),
    ]
