# Generated by Django 6.1 on 2026-08-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_alter_discount_code_alter_servicedetail_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá'),
        ),
    ]
