# Generated by Django 6.1 on 2026-08-24 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_alter_discount_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='category',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='chair_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_detail',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='appointment_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian khám'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20, verbose_name='Trạng thái')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='booking.booking')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.employee')),
            ],
            options={
                'db_table': 'db_table_booking_status_history',
            },
        ),
        migrations.DeleteModel(
            name='BookingStatus',
        ),
    ]
