# Generated by Django 6.1 on 2026-08-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_remove_booking_booking_date_remove_booking_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='dob',
            new_name='customer_dob',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Giới tính'),
        ),
        migrations.AddField(
            model_name='customer',
            name='patient_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã bệnh nhân'),
        ),
    ]
