# Generated by Django 6.1 on 2026-08-25 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_rename_dob_customer_customer_dob_and_more'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE db_table_customers RENAME COLUMN full_name TO name;'),
        migrations.RunSQL('ALTER TABLE db_table_customers RENAME COLUMN dob TO customer_dob;'),
    ]
