# Generated by Django 6.1 on 2026-08-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_rename_cols_in_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingstatushistory',
            old_name='changed_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='bookingstatushistory',
            old_name='history_id',
            new_name='status_id',
        ),
        migrations.RemoveField(
            model_name='bookingstatushistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='bookingstatushistory',
            name='notes',
        ),
        migrations.AddField(
            model_name='booking',
            name='estimated_duration',
            field=models.IntegerField(blank=True, help_text='Th?i l??ng d? ki?n (ph?t)', null=True),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi ch?'),
        ),
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Tr?ng th?i'),
        ),
    ]
