# Generated by Django 6.1 on 2026-08-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_rename_changed_at_bookingstatushistory_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='manual_total',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='appointment_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ kết thúc'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ bắt đầu'),
        ),
    ]
