# Generated by Django 6.1 on 2026-08-26 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_rename_created_on_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.servicecategory', verbose_name='Danh mục'),
        ),
    ]
