# Generated by Django 6.1 on 2026-08-27 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_booking_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Nhân viên tạo booking (Null nếu khách tự đặt trên web)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='estimated_duration',
            field=models.IntegerField(blank=True, help_text='Thời lượng dự kiến (phút)', null=True),
        ),
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Trạng thái'),
        ),
    ]
