# Generated by Django 6.1 on 2026-08-27 09:54

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_booking_created_by_alter_booking_estimated_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'verbose_name': 'HÃ³a Ä‘Æ¡n Káº¿ toÃ¡n', 'verbose_name_plural': 'HÃ³a Ä‘Æ¡n Káº¿ toÃ¡n'},
        ),
        migrations.AlterModelOptions(
            name='bookingdetail',
            options={'verbose_name': 'Dá»‹ch vá»¥ trong Lá»‹ch', 'verbose_name_plural': 'CÃ¡c dá»‹ch vá»¥'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Khuyáº¿n mÃ£i', 'verbose_name_plural': 'Khuyáº¿n mÃ£i'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Danh má»¥c Dá»‹ch vá»¥', 'verbose_name_plural': 'Danh má»¥c Dá»‹ch vá»¥'},
        ),
        migrations.AlterModelOptions(
            name='servicedetail',
            options={'verbose_name': 'Chi tiáº¿t Dá»‹ch vá»¥', 'verbose_name_plural': 'Chi tiáº¿t Dá»‹ch vá»¥'},
        ),
        migrations.AlterModelOptions(
            name='topupinfo',
            options={'verbose_name': 'Cáº¥u hÃ¬nh Thanh toÃ¡n', 'verbose_name_plural': 'Cáº¥u hÃ¬nh Thanh toÃ¡n'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_by',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='NhÃ¢n viÃªn táº¡o booking (Null náº¿u khÃ¡ch tá»± Ä‘áº·t trÃªn web)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ná»™i dung'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', 'Báº£n nhÃ¡p'), ('Published', 'Xuáº¥t báº£n')], default='Draft', max_length=20, verbose_name='Tráº¡ng thÃ¡i'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='TiÃªu Ä‘á»\x81'),
        ),
        migrations.AlterField(
            model_name='article',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='temp/', verbose_name='Táº£i lÃªn File Word (.docx)'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sá»‘ tiá»\x81n Ä‘iá»\x81u chá»‰nh'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='booking.booking', verbose_name='Lá»‹ch khÃ¡m'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.discount', verbose_name='Khuyáº¿n mÃ£i'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='final_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sá»‘ tiá»\x81n cuá»‘i cÃ¹ng'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tá»•ng tiá»\x81n gá»‘c (Há»‡ thá»‘ng tÃ\xadnh)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.servicecategory', verbose_name='Danh má»¥c'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giá»\x9d káº¿t thÃºc'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='estimated_duration',
            field=models.IntegerField(blank=True, help_text='Thá»\x9di lÆ°á»£ng dá»± kiáº¿n (phÃºt)', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chÃº'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giá»\x9d báº¯t Ä‘áº§u'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=20, verbose_name='Tráº¡ng thÃ¡i'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='actual_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ä\x90Æ¡n giÃ¡'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'Doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.employee', verbose_name='BÃ¡c sÄ© khÃ¡m'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Sá»‘ lÆ°á»£ng'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='service_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.servicedetail', verbose_name='Dá»‹ch vá»¥'),
        ),
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chÃº'),
        ),
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Tráº¡ng thÃ¡i'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Ä\x90á»‹a chá»‰'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=100, verbose_name='TÃªn chi nhÃ¡nh'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='total_chairs',
            field=models.IntegerField(default=5, verbose_name='Tá»•ng sá»‘ gháº¿'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Ä\x90á»‹a chá»‰'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_dob',
            field=models.DateField(blank=True, null=True, verbose_name='NgÃ\xa0y sinh'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Giá»›i tÃ\xadnh'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Há»\x8d vÃ\xa0 tÃªn'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='patient_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='MÃ£ bá»‡nh nhÃ¢n'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='Sá»‘ Ä‘iá»‡n thoáº¡i'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='MÃ£ giáº£m giÃ¡'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='MÃ´ táº£'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('Percent', 'Pháº§n trÄƒm'), ('Fixed', 'Sá»‘ tiá»\x81n')], default='Percent', max_length=20, verbose_name='Loáº¡i giáº£m giÃ¡'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Tráº¡ng thÃ¡i'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='GiÃ¡ trá»‹'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Há»\x8d vÃ\xa0 tÃªn'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sá»‘ Ä‘iá»‡n thoáº¡i'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Reception', 'Reception'), ('Marketing', 'Marketing')], default='Doctor', max_length=20, verbose_name='Vai trÃ²'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ChuyÃªn mÃ´n'),
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PhÃ¢n loáº¡i'),
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='item_name',
            field=models.CharField(max_length=255, verbose_name='TÃªn váº\xadt tÆ°'),
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='GiÃ¡ vá»‘n'),
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='unit',
            field=models.CharField(max_length=50, verbose_name='Ä\x90Æ¡n vá»‹ tÃ\xadnh'),
        ),
        migrations.AlterField(
            model_name='inventoryusage',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.employee', verbose_name='NgÆ°á»\x9di xuáº¥t/sá»\xad dá»¥ng'),
        ),
        migrations.AlterField(
            model_name='inventoryusage',
            name='quantity_used',
            field=models.PositiveIntegerField(verbose_name='Sá»‘ lÆ°á»£ng dÃ¹ng'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sá»‘ tiá»\x81n'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('QR Code', 'QR Code'), ('Cash', 'Cash'), ('Card', 'Card')], default='QR Code', max_length=50, verbose_name='PhÆ°Æ¡ng thá»©c'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='estimate_time',
            field=models.IntegerField(default=30, verbose_name='Thá»\x9di gian Æ°á»›c tÃ\xadnh (phÃºt)'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='TÃªn danh má»¥c'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='booking.servicecategory', verbose_name='Danh má»¥c'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MÃ£ dá»‹ch vá»¥'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='difficulty',
            field=models.CharField(choices=[('CÆ¡ báº£n', 'CÆ¡ báº£n'), ('Dá»…', 'Dá»…'), ('Trung bÃ¬nh', 'Trung bÃ¬nh'), ('KhÃ³', 'KhÃ³'), ('Phá»©c táº¡p', 'Phá»©c táº¡p')], default='CÆ¡ báº£n', max_length=50, verbose_name='Ä\x90á»™ khÃ³'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='name',
            field=models.CharField(max_length=255, verbose_name='TÃªn dá»‹ch vá»¥ chi tiáº¿t'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='GiÃ¡'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Báº£o hÃ\xa0nh'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(verbose_name='Thá»\x9di gian káº¿t thÃºc'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(verbose_name='Thá»\x9di gian báº¯t Ä‘áº§u'),
        ),
        migrations.AlterField(
            model_name='topupinfo',
            name='account_name',
            field=models.CharField(max_length=100, verbose_name='TÃªn tÃ\xa0i khoáº£n'),
        ),
        migrations.AlterField(
            model_name='topupinfo',
            name='account_number',
            field=models.CharField(max_length=50, verbose_name='Sá»‘ tÃ\xa0i khoáº£n'),
        ),
        migrations.AlterField(
            model_name='topupinfo',
            name='bank_name',
            field=models.CharField(max_length=50, verbose_name='TÃªn ngÃ¢n hÃ\xa0ng (MÃ£)'),
        ),
        migrations.AlterField(
            model_name='topupinfo',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Máº·c Ä‘á»‹nh'),
        ),
    ]
