# Generated by Django 6.1 on 2026-08-29 03:19

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0038_alter_billing_options_alter_bookingdetail_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'verbose_name': 'Hóa đơn Kế toán', 'verbose_name_plural': 'Hóa đơn Kế toán'},
        ),
        migrations.AlterModelOptions(
            name='bookingdetail',
            options={'verbose_name': 'Dịch vụ trong Lịch', 'verbose_name_plural': 'Các dịch vụ'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Khuyến mãi', 'verbose_name_plural': 'Khuyến mãi'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Danh mục Dịch vụ', 'verbose_name_plural': 'Danh mục Dịch vụ'},
        ),
        migrations.AlterModelOptions(
            name='servicedetail',
            options={'verbose_name': 'Chi tiết Dịch vụ', 'verbose_name_plural': 'Chi tiết Dịch vụ'},
        ),
        migrations.AlterModelOptions(
            name='topupinfo',
            options={'verbose_name': 'Cấu hình Thanh toán', 'verbose_name_plural': 'Cấu hình Thanh toán'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', 'Bản nháp'), ('Published', 'Xuất bản')], default='Draft', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='article',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='temp/', verbose_name='Tải lên File Word (.docx)'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Số tiền điều chỉnh'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='booking.booking', verbose_name='Lịch khám'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.discount', verbose_name='Khuyến mãi'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='final_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Số tiền cuối cùng'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng tiền gốc (Hệ thống tính)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.servicecategory', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='Nhân viên tạo booking (Null nếu khách tự đặt trên web)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ kết thúc'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='estimated_duration',
            field=models.IntegerField(blank=True, help_text='Thời lượng dự kiến (phút)', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ bắt đầu'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='actual_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Đơn giá'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'Doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.employee', verbose_name='Bác sĩ khám'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='service_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.servicedetail', verbose_name='Dịch vụ'),
        ),
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên chi nhánh'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='total_chairs',
            field=models.IntegerField(default=5, verbose_name='Tổng số ghế'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_dob',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='patient_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã bệnh nhân'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('Percent', 'Phần trăm'), ('Fixed', 'Số tiền')], default='Percent', max_length=20, verbose_name='Loại giảm giá'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá trị'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Reception', 'Reception'), ('Marketing', 'Marketing')], default='Doctor', max_length=20, verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chuyên môn'),
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phân loại'),
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='item_name',
            field=models.CharField(max_length=255, verbose_name='Tên vật tư'),
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Giá vốn'),
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='unit',
            field=models.CharField(max_length=50, verbose_name='Đơn vị tính'),
        ),
        migrations.AlterField(
            model_name='inventoryusage',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.employee', verbose_name='Người xuất/sử dụng'),
        ),
        migrations.AlterField(
            model_name='inventoryusage',
            name='quantity_used',
            field=models.PositiveIntegerField(verbose_name='Số lượng dùng'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('QR Code', 'QR Code'), ('Cash', 'Cash'), ('Card', 'Card')], default='QR Code', max_length=50, verbose_name='Phương thức'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='estimate_time',
            field=models.IntegerField(default=30, verbose_name='Thời gian ước tính (phút)'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên danh mục'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='booking.servicecategory', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã dịch vụ'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='difficulty',
            field=models.CharField(choices=[('Cơ bản', 'Cơ bản'), ('Dễ', 'Dễ'), ('Trung bình', 'Trung bình'), ('Khó', 'Khó'), ('Phức tạp', 'Phức tạp')], default='Cơ bản', max_length=50, verbose_name='Độ khó'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên dịch vụ chi tiết'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bảo hành'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(verbose_name='Thời gian kết thúc'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(verbose_name='Thời gian bắt đầu'),
        ),
        migrations.AlterField(
            model_name='topupinfo',
            name='account_name',
            field=models.CharField(max_length=100, verbose_name='Tên tài khoản'),
        ),
        migrations.AlterField(
            model_name='topupinfo',
            name='account_number',
            field=models.CharField(max_length=50, verbose_name='Số tài khoản'),
        ),
        migrations.AlterField(
            model_name='topupinfo',
            name='bank_name',
            field=models.CharField(max_length=50, verbose_name='Tên ngân hàng (Mã)'),
        ),
        migrations.AlterField(
            model_name='topupinfo',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Mặc định'),
        ),
    ]
