# Generated by Django 6.1 on 2026-08-31 02:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0039_alter_billing_options_alter_bookingdetail_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Ảnh Thumbnail (Tải lên)'),
        ),
    ]
