# Generated by Django 6.1 on 2026-09-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0040_remove_article_thumbnail_url_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('kien-thuc', 'Kiến thức y khoa'), ('khuyen-mai', 'Khuyến mại')], default='kien-thuc', max_length=50, verbose_name='Chuyên mục'),
        ),
    ]
