# Generated by Django 6.1 on 2026-09-03 02:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='word_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Tài liệu Word'),
        ),
    ]
