# Generated by Django 6.1 on 2026-09-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_alter_article_word_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.CharField(choices=[('dich-vu', 'Dịch vụ'), ('blog', 'Tin tức & Blog'), ('thong-tin', 'Thông tin phòng khám')], default='blog', max_length=20, verbose_name='Khu vực (Menu 1)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('kien-thuc', 'Kiến thức y khoa'), ('khuyen-mai', 'Khuyến mại'), ('nieng-rang', 'Niềng răng - Chỉnh nha'), ('nho-rang', 'Nhổ răng khôn')], default='kien-thuc', max_length=50, verbose_name='Chuyên mục'),
        ),
    ]
