# Generated by Django 6.1 on 2026-09-04 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0043_article_section_alter_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='contact@minhsinhdental.com', max_length=254, verbose_name='Email')),
                ('working_hours', models.CharField(default='08:00 - 18:00 (Thứ 2 - CN)', max_length=255, verbose_name='Giờ làm việc')),
                ('branch_section_title', models.CharField(default='HỆ THỐNG CƠ SỞ', max_length=100, verbose_name='Tiêu đề Cột Cơ sở')),
                ('social_section_title', models.CharField(default='KẾT NỐI VỚI CHÚNG TÔI', max_length=100, verbose_name='Tiêu đề Cột MXH')),
            ],
            options={
                'verbose_name': 'Cấu hình Website',
                'verbose_name_plural': 'Cấu hình Website',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='section',
        ),
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tiêu đề Menu')),
                ('url', models.CharField(max_length=255, verbose_name='Đường dẫn (URL)')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='booking.menulink', verbose_name='Menu Cha (Để trống nếu là Menu gốc)')),
            ],
            options={
                'verbose_name': 'Menu Điều Hướng',
                'verbose_name_plural': 'Menu Điều Hướng',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.menulink', verbose_name='Chuyên mục (Menu gốc)'),
        ),
        migrations.CreateModel(
            name='ClinicBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Cơ sở 1', max_length=100, verbose_name='Tên cơ sở (VD: Trụ sở chính)')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('hotline', models.CharField(max_length=20, verbose_name='Hotline')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='booking.sitesettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên MXH (VD: Facebook, Zalo)')),
                ('url', models.URLField(verbose_name='Đường dẫn')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='booking.sitesettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
