# Generated by Django 6.1 on 2026-09-04 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0044_sitesettings_remove_article_section_menulink_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menulink',
            options={'ordering': ['order'], 'verbose_name': 'Cấu hình Header', 'verbose_name_plural': 'Cấu hình Header'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Cấu hình Footer', 'verbose_name_plural': 'Cấu hình Footer'},
        ),
    ]
