# Generated by Django 6.1 on 2026-09-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0045_alter_menulink_options_alter_sitesettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='banner_image',
            field=models.FileField(blank=True, null=True, upload_to='raw/upload/', verbose_name='Ảnh Banner riêng (Trống = dùng Thumbnail)'),
        ),
        migrations.AddField(
            model_name='article',
            name='show_banner',
            field=models.BooleanField(default=True, verbose_name='Hiển thị Banner bài viết'),
        ),
    ]
