# Generated by Django 6.1 on 2026-09-05 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0046_article_banner_image_article_show_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='sub_total',
        ),
        migrations.AddField(
            model_name='billing',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú thu ngân'),
        ),
        migrations.AddField(
            model_name='billing',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền gốc'),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='tooth_position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vị trí răng'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='adjustment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Điều chỉnh (+/-)'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.discount', verbose_name='Mã giảm giá'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='final_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thành tiền'),
        ),
    ]
