# Generated by Django 6.1 on 2026-08-24 03:37

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0030_alter_discount_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogDiscount',
            fields=[
            ],
            options={
                'verbose_name': 'Khuyến mãi',
                'verbose_name_plural': 'Khuyến mãi',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('booking.discount',),
        ),
        migrations.CreateModel(
            name='CatalogServiceDetail',
            fields=[
            ],
            options={
                'verbose_name': 'Bảng chi tiết',
                'verbose_name_plural': 'Bảng chi tiết',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('booking.servicedetail',),
        ),
    ]
