# Generated by Django 6.1 on 2026-08-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogservicedetail',
            options={'verbose_name': 'Báº£ng chi tiáº¿t', 'verbose_name_plural': 'Báº£ng chi tiáº¿t'},
        ),
    ]
