# Generated by Django 6.1 on 2026-08-29 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_menu', '0002_alter_catalogservicedetail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogservicedetail',
            options={'verbose_name': 'Bảng chi tiết', 'verbose_name_plural': 'Bảng chi tiết'},
        ),
    ]
